### ISSUE TITLE
소스엔 <title> 내용이 있는데 홈페이지엔 없네요.

### ISSUE THREAD

**Issue by TaekSoonJang** [code-squad/code-squad.github.io#1]
왜 그럴까요? ㅠㅠ

**Comment by songsl** [comment]
@TaekSoonJang  홈페이지가 iframe으로 여기를 wrapping하고 있고 iframe으로 쌓인 페이지에 <title>과 favicon이 없기 때문입니다. :-) 지나가다..

**Comment by code-squad** [comment]
리다이렉트 하느라 그런겅께~ 곧 해결될 거 같네요~
